### PR TITLE
Tailwind v3 colors

### PR DESCRIPTION
**Pull request by albemala**
**Extracted tailwind v1 colors into separate file**: I think this change makes the code more clear and easier to maintain.

**Set up linter**: I'm using `very_good_analysis`, which uses a stricter set of rules compared to the Flutter standard one.

**Added Tailwind v3 colors**: In Tailwind v3 they have changed some color names. I've also added a script that automatically generates the corresponding Dart class.

**Added tests**: Just some unit tests to verify that colors are valid.

Please let me know if these changes are okay. I'm open to suggestions in case you want to change something.

Thank you!

@MBeliou @nhedger

### CODE REVIEW

**Comment by MBeliou** [comment]
Hi, quite busy atm but I'll try and get a look at your PR during the week.

**Comment by albemala** [comment]
No worries, no rush! Thanks for checking this out.

**Comment by MBeliou** [comment]
lgtm, thank you for your work

**Comment by albemala** [comment]
Thank you!

**Pull request merged**
